name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ngtn-tiennguyen
          SETTING_JSON: |
            {
              "githubUserName": "ngtn-tiennguyen",
              "backgroundColor": "#0d1117"
            }

      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A .
          git diff --cached --quiet || git commit -m "update: 3d contribution calendar"
          git push
